### ISSUE TITLE
Checklist voor 2022-2023

### ISSUE THREAD

**Issue by Derkades** [UvA-FNWI/byod-wiki#1]
- [x] Windows 11 fast startup stappen
- [x] Windows 11 bitlocker stappen en screenshots
- [ ] Intel Arc GPU, werkt het? Indien niet, hoe dan toch?
- [ ] Is RTL8821CE driver in de kernel nog steeds stuk, waardoor dkms driver workaround nodig was?
- [x] Misschien USBWriter vervangen door een alternatief, laatste update was in 2015. Het liefst eentje die de USB weer terugleest om de inhoud te verifieren
- [ ] macOS shell script?
- [x] Zoom en teams via flatpak in plaats van losse debs zonder updates
- [x] Moeten we nog wel LaTeX lokaal installeren nu iedereen (?) overleaf gebruikt (update: latex is nu uit het shell script)
- [x] SIM-PL package voor `jammy` uploaden naar launchpad https://launchpad.net/~uva-informatica/+archive/ubuntu/sim-pl
- [x] Worden de [meta packages](https://launchpad.net/~uva-informatica/+archive/ubuntu/meta-packages) nog wel gebruikt? Volgens mij kunnen ze uit het shell script
